# Generated by Django 5.2.3 on 2025-12-23 19:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_value', models.CharField(default='MAX', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price Range',
                'verbose_name_plural': 'Price Ranges',
                'ordering': ['from_value'],
                'unique_together': {('from_value', 'to_value')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key_enc', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('scraping_enabled', models.BooleanField(default=True)),
                ('scraping_interval_hours', models.IntegerField(default=24)),
                ('last_scrape_time', models.DateTimeField(blank=True, null=True)),
                ('price_update_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='marketplace.marketplace')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings_by_vendor', to='marketplace.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory_settings', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Store Inventory Settings',
                'verbose_name_plural': 'Store Inventory Settings',
                'unique_together': {('store', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='StorePriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_tax_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marketplace_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_margin_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_settings_by_vendor', to='marketplace.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_price_settings', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Store Price Settings',
                'verbose_name_plural': 'Store Price Settings',
                'unique_together': {('store', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='InventoryRangeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_multiplier', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.pricerange')),
                ('inventory_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_range_multipliers', to='marketplace.storeinventorysettings')),
            ],
            options={
                'verbose_name': 'Inventory Range Multiplier',
                'verbose_name_plural': 'Inventory Range Multipliers',
                'ordering': ['price_range__from_value'],
                'unique_together': {('inventory_settings', 'price_range')},
            },
        ),
        migrations.CreateModel(
            name='PriceRangeMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dont_pay_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.pricerange')),
                ('price_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_range_margins', to='marketplace.storepricesettings')),
            ],
            options={
                'verbose_name': 'Price Range Margin',
                'verbose_name_plural': 'Price Range Margins',
                'ordering': ['price_range__from_value'],
                'unique_together': {('price_settings', 'price_range')},
            },
        ),
    ]
