# Generated by Django 5.2.3 on 2025-12-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sku', models.CharField(help_text='Vendor SKU/item number', max_length=255)),
                ('variation_id', models.CharField(blank=True, help_text='Product variation identifier if applicable', max_length=255)),
                ('marketplace_child_sku', models.CharField(help_text='Marketplace-specific child SKU', max_length=255)),
                ('marketplace_parent_sku', models.CharField(blank=True, help_text='Marketplace-specific parent SKU', max_length=255)),
                ('marketplace_external_id', models.CharField(blank=True, help_text='External ID from marketplace (eBay ID, Amazon ASIN, etc.)', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('vendor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_stock', models.IntegerField(blank=True, null=True)),
                ('calculated_stock', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('scrape_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(help_text='The marketplace where this product is listed', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.marketplace')),
                ('store', models.ForeignKey(help_text='The store where this product is listed', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.store')),
                ('vendor', models.ForeignKey(help_text='The vendor who supplies this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_products', models.IntegerField(default=0)),
                ('successful_scrapes', models.IntegerField(default=0)),
                ('failed_scrapes', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='marketplace.store')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Scrape',
                'verbose_name_plural': 'Scrapes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scraped_stock', models.IntegerField(blank=True, null=True)),
                ('scraped_title', models.CharField(blank=True, max_length=500)),
                ('scraped_data', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_results', to='products.product')),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='products.scrape')),
            ],
            options={
                'verbose_name': 'Scrape Result',
                'verbose_name_plural': 'Scrape Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='marketplace.store')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='The upload batch that created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.upload'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'vendor_sku', 'store')},
        ),
    ]
